version: "3.7"
services:
  frontend:
    build:
      context: ./Productivus-Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./Productivus-Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
